name: Node CI

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

concurrency:
    group: ci-${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true

jobs:
    node-ci:
        name: Node CI

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"

            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn pretty:check
            - run: yarn build
            - run: yarn test --coverage
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                  fail_ci_if_error: true
