name: CI

permissions:
    contents: read
    actions: write

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

concurrency:
    group: ci-${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true

jobs:
    ci:
        name: CI

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2.1.3

            - run: bun install
            - run: bun run lint
            - run: bun run pretty:check
            - run: bun run build
            - run: bun test --coverage
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                  fail_ci_if_error: true
